# Generated by Django 3.2.5 on 2021-07-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210726_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='todo',
        ),
    ]
