# Generated by Django 3.2.5 on 2021-07-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210726_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ManyToManyField(to='todo.Todo'),
        ),
    ]
