# Generated by Django 3.2.5 on 2021-07-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210726_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
