# Generated by Django 3.2.5 on 2021-07-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
